Merge from trunk. Merge log:
Merged revisions 2002-2053,2055-2064,2068-2069 via svnmerge from 
https://phc.googlecode.com/svn/trunk

........
  r2002 | paul.biggar | 2008-12-04 12:48:01 +0000 (Thu, 04 Dec 2008) | 2 lines
  
  Ignore further fails in the XML-roundtrip test. We ignored <value>TLE0</value> where there suffix was differet (due to different invocation order). Also ignore <string>TLE0</string>, for the same reason.
........
  r2003 | paul.biggar | 2008-12-04 12:56:45 +0000 (Thu, 04 Dec 2008) | 4 lines
  
  Merge changes to Generate_C from dataflow to trunk.
  
  Principally, this allows rvalues on the RHS of expressions. This is allowed on the dataflow branch due to constant propagation, but not on trunk. However, I need to sychronize the two, so that the refactoring of Generate_C is not too difficult to merge back to dataflow, and takes the changes into account.
........
  r2004 | paul.biggar | 2008-12-04 14:22:01 +0000 (Thu, 04 Dec 2008) | 2 lines
  
  Move escape functions to a common location: src/lib/escape.{h,cpp}
........
  r2005 | paul.biggar | 2008-12-04 15:59:53 +0000 (Thu, 04 Dec 2008) | 4 lines
  
  Move the analysis part of constant pooling to a pre-pass.
  
  Fix an XML parser bug, where string-lists didnt have '\n' between members.
........
  r2006 | paul.biggar | 2008-12-04 16:33:14 +0000 (Thu, 04 Dec 2008) | 2 lines
  
  Move much of the pooled-literal creation to use the annotated attributes.
........
  r2007 | paul.biggar | 2008-12-04 18:53:39 +0000 (Thu, 04 Dec 2008) | 2 lines
  
  Simplify codegen of literals slightly, removing 1 template parameter.
........
  r2008 | paul.biggar | 2008-12-05 01:10:59 +0000 (Fri, 05 Dec 2008) | 4 lines
  
  Store copies of the Literals in the PHP script's attributes. The names are then stored in the Literals' attributes. This will make it easier to initialize constants eagerly, cleaning up portions of the Generate_C code.
  
  Fix the XML unparser to support Lists of IR::Nodes.
........
  r2009 | paul.biggar | 2008-12-05 01:48:31 +0000 (Fri, 05 Dec 2008) | 4 lines
  
  Remove use of the literal specializers. I'll remove the specializers themselves next.
  
  This moves initialization of pooled literals to code generation at the start of the program, where they probably belong.
........
  r2010 | paul.biggar | 2008-12-05 02:15:36 +0000 (Fri, 05 Dec 2008) | 2 lines
  
  Remove all remnants of the Literal Specializer. It was an awful hack, and I'm glad to see it gone.
........
  r2011 | paul.biggar | 2008-12-05 15:05:47 +0000 (Fri, 05 Dec 2008) | 2 lines
  
  MIR::Return can take an Rvalue if the function is not return-by-reference (so, the same as parameters).
........
  r2012 | paul.biggar | 2008-12-05 15:57:17 +0000 (Fri, 05 Dec 2008) | 2 lines
  
  Remove the cleanup function, and the is_var_new from declare(). Instead, inline it all. This will allow them be removed one-by-one.
........
  r2013 | paul.biggar | 2008-12-05 17:27:11 +0000 (Fri, 05 Dec 2008) | 7 lines
  
  Add a test for returning Rvalues. Fix fallout. I hadnt kept the HIR in line with the MIR, or fixed folding of the HIR.
  
  Also codegen for:
  	$$x = 5;
  
  But not	function_call (5);, which needs more work.
........
  r2014 | paul.biggar | 2008-12-05 17:43:48 +0000 (Fri, 05 Dec 2008) | 4 lines
  
  Nearly all uses to is_X_new go through write_var. So make a separate version which doesnt use it, which  we call write_var. The old version is renamed to write_var_TODO. All calls are changed to call write_var_TODO, so that I can change them back one-by-one.
  
  The new write_var uses sep_change_on_write instead of is_X_new. It is the only caller to sep_change_on_write, so remove the 'in_change_on_write' check in sep_change_on_write. In the case of write_var, it must be in the change on write set, or else is_ref would not be set.
........
  r2015 | paul.biggar | 2008-12-05 19:32:23 +0000 (Fri, 05 Dec 2008) | 2 lines
  
  Remove 3 calls to write_var_TODO. This also fixes 3 tests, probably due to memory leaks.
........
  r2016 | paul.biggar | 2008-12-05 22:34:54 +0000 (Fri, 05 Dec 2008) | 4 lines
  
  Fix the logic of returning by reference. The comments made little sense, and what did work, appeared to work by magic.
  
  zvp_clone_ex now returns its clone, rather than overwriting it in place. This means that when we pass a p_rhs to write_var, we do not alter the initial p_rhs.
........
  r2017 | paul.biggar | 2008-12-06 00:52:10 +0000 (Sat, 06 Dec 2008) | 2 lines
  
  We were incorrectly unparsing Param_is_ref which had targets. This was due to the convaluted way we have to fold the MIR to the AST (RE VARIABLE_NAMEs). Its simple to call unparse anyway, so no harm.
........
  r2018 | paul.biggar | 2008-12-06 01:08:33 +0000 (Sat, 06 Dec 2008) | 2 lines
  
  Fix indenting.
........
  r2019 | paul.biggar | 2008-12-06 02:18:16 +0000 (Sat, 06 Dec 2008) | 2 lines
  
  Do MIR uppering for Param_is_ref with a VARIABLE_NAME as a target (note: CLASS_NAME as target not done yet).
........
  r2020 | paul.biggar | 2008-12-06 12:08:47 +0000 (Sat, 06 Dec 2008) | 2 lines
  
  Remove is_p_rhs_new from Method_invocation codegen. Instead, reuse the same condition. Make the comments a little bit clearer.
........
  r2021 | paul.biggar | 2008-12-06 13:18:11 +0000 (Sat, 06 Dec 2008) | 2 lines
  
  Add details of how to run PHP's phpt tests.
........
  r2022 | paul.biggar | 2008-12-06 13:32:31 +0000 (Sat, 06 Dec 2008) | 2 lines
  
  Follow symbolics links when finding test scripts.
........
  r2023 | paul.biggar | 2008-12-06 13:33:58 +0000 (Sat, 06 Dec 2008) | 2 lines
  
  Rather than trying to take note of each possible error that needs to be homogenized, it is best to always remove the subject of the test, replacing it with __FILENAME__ (not that it would be executed, but its as good a token as any).
........
  r2024 | paul.biggar | 2008-12-06 13:36:18 +0000 (Sat, 06 Dec 2008) | 5 lines
  
  Fix a number of errors related to __METHOD__ and __FILENAME__:
  	__METHOD__ should include the classname (claasname::method_name)
  	in global scope, __METHOD__, __FUNCTION__ and __CLASS__ should resolve to ""
  	when leaving a method or class, __FUNCTION__ etc should be reset to ""
........
  r2025 | paul.biggar | 2008-12-06 14:34:01 +0000 (Sat, 06 Dec 2008) | 5 lines
  
  Fix XML_roundtrip.
  
  Add support for nodelist to the XML parser.
  We did not support attributes nested within other attributes (say, if a node was an attribute and it the node had attributes as well). The key of the inner attribute was used for the outer attribute. This adds a key stack to fix it.
........
  r2026 | paul.biggar | 2008-12-06 15:10:42 +0000 (Sat, 06 Dec 2008) | 4 lines
  
  Revert change to homogenize_filenames_and_line_numbers. Cases like "Fatal error: Unknown: ..." were better handled the old way.
........
  r2027 | paul.biggar | 2008-12-06 15:17:35 +0000 (Sat, 06 Dec 2008) | 2 lines
  
  Remove some uses of is_zvp_new.
........
  r2028 | paul.biggar | 2008-12-06 15:27:55 +0000 (Sat, 06 Dec 2008) | 2 lines
  
  Remove all is_new, except those involving get_var_var.
........
  r2029 | paul.biggar | 2008-12-06 15:40:19 +0000 (Sat, 06 Dec 2008) | 2 lines
  
  I believe that setting is_new is incorrect in get_var_var. This appears to be true, in the sense that 4 tests are fixed when it is removed. This is the final hurdle to completely getting rid of is_zvp_new. I hope it will be removed in the next patch.
........
  r2030 | paul.biggar | 2008-12-06 16:00:21 +0000 (Sat, 06 Dec 2008) | 4 lines
  
  Remove is_new from get_var_var.
  
  I was mistaken to say this was the last use of it. Actually, its in read_array too. It will be disposed of shortly, I hope.
........
  r2031 | paul.biggar | 2008-12-06 16:46:28 +0000 (Sat, 06 Dec 2008) | 2 lines
  
  Sort-of remove the final is_new. This makes it local to the code for which it is generated. It is still needed for that code, however.
........
  r2032 | paul.biggar | 2008-12-06 17:08:52 +0000 (Sat, 06 Dec 2008) | 2 lines
  
  Change the signature of write_var. rhs is now a zval*, not a zval**. Change all callers.
........
  r2033 | paul.biggar | 2008-12-06 17:16:24 +0000 (Sat, 06 Dec 2008) | 2 lines
  
  Remove unused functions.
........
  r2034 | paul.biggar | 2008-12-06 17:27:03 +0000 (Sat, 06 Dec 2008) | 2 lines
  
  Remove declare. Convert method_invocation to use zval* rhs, instead of zval** p_rhs.
........
  r2035 | paul.biggar | 2008-12-06 22:28:10 +0000 (Sat, 06 Dec 2008) | 6 lines
  
  Expand the ini setting processing.
  
  The sets command-line .ini settings (-d) to the embed SAPI. get_include_paths gets the include_path setting, which is used in Process_includes.
  
  The tests all need -d settings, so we give them the same settings as the PHP interpreter uses.
........
  r2036 | paul.biggar | 2008-12-06 22:58:09 +0000 (Sat, 06 Dec 2008) | 2 lines
  
  Add a check for invalid key/value pairs. The '/' needs to be escaped by preg_quote, which it isnt by default.
........
  r2037 | paul.biggar | 2008-12-07 11:32:36 +0000 (Sun, 07 Dec 2008) | 3 lines
  
  Fix placement of labels for continues and breaks in foreach lowering. We incorrectly made continue jump out of the loop.
  When printing MIR, put labels one column back, making it easier to read.
........
  r2038 | paul.biggar | 2008-12-07 11:38:30 +0000 (Sun, 07 Dec 2008) | 2 lines
  
  Scale up the push_uninitialized test (also the test case for continue from foreach). Handle (I think) all cases involving scalars and uninitialized vars.
........
  r2039 | paul.biggar | 2008-12-07 12:46:40 +0000 (Sun, 07 Dec 2008) | 2 lines
  
  Support require (TODO: include_once and require_once).
........
  r2040 | paul.biggar | 2008-12-07 12:56:19 +0000 (Sun, 07 Dec 2008) | 2 lines
  
  Keep track of altered .ini values from the command-line, and set them at run-time in the generated code. This is the only means for an executable to get its ini settings, since a -d command-line parameter isnt supported at run-time.
........
  r2041 | paul.biggar | 2008-12-07 15:18:56 +0000 (Sun, 07 Dec 2008) | 2 lines
  
  Move the 'analysis' part of function caches into the annotations pre-pass.
........
  r2042 | paul.biggar | 2008-12-07 15:19:52 +0000 (Sun, 07 Dec 2008) | 2 lines
  
  Exclude from strip-includes a test which is designed to fail, 
........
  r2043 | paul.biggar | 2008-12-07 19:03:55 +0000 (Sun, 07 Dec 2008) | 4 lines
  
  Handle assigning into a string (and all other scalar combinations).
  
  indexing_non_arrays now works, and its 42000 lines of output are all correct.
........
  r2044 | paul.biggar | 2008-12-07 21:16:28 +0000 (Sun, 07 Dec 2008) | 2 lines
  
  Fix memory leak in builtin_include/require. We were leaking the return value.
........
  r2045 | paul.biggar | 2008-12-08 11:36:27 +0000 (Mon, 08 Dec 2008) | 4 lines
  
  Nearly all of the Demi_eval failures were false positives. The MIR has changed a lot since I wrote the test, and it was complaining of many things along the lines of "param_is_ref is not a function".
  
  The other failure was our compiled code gave a filename and line number to errors, which PHP didnt. This is homogenized now.
........
  r2046 | paul.biggar | 2008-12-08 19:20:14 +0000 (Mon, 08 Dec 2008) | 2 lines
  
  Handle all unsets except var-vars. This handles unsets with an arbitrary number of indices, and expands the test for it considerably.
........
  r2047 | paul.biggar | 2008-12-08 19:26:37 +0000 (Mon, 08 Dec 2008) | 2 lines
  
  Avoid a segfault when calling echo through a print which uses a return value.
........
  r2048 | paul.biggar | 2008-12-08 19:54:35 +0000 (Mon, 08 Dec 2008) | 2 lines
  
  Fix bug where multiple parameters have the same name.
........
  r2049 | paul.biggar | 2008-12-08 21:10:19 +0000 (Mon, 08 Dec 2008) | 2 lines
  
  Split runtime/support_routines into files reflecting their uses. Most of the functions have too many uses, and this makes it clearer what belongs where. This idea is to inline most of these into a single call based on pattern, and this is moving in that direction.
........
  r2050 | paul.biggar | 2008-12-08 21:16:56 +0000 (Mon, 08 Dec 2008) | 2 lines
  
  When unparsing code for comments in the generated code, dont escape tabs. This makes it more readable.
........
  r2051 | paul.biggar | 2008-12-08 21:18:01 +0000 (Mon, 08 Dec 2008) | 2 lines
  
  Fix a value being overwritten when its old value is the result of a foreach_get_val.
........
  r2052 | paul.biggar | 2008-12-08 21:40:30 +0000 (Mon, 08 Dec 2008) | 2 lines
  
  Put in a better workaround for refcounts being reset by the Zend engine. This fixes all the return-by-reference tests, except one, whose bug in unrelated.
........
  r2053 | paul.biggar | 2008-12-09 00:08:41 +0000 (Tue, 09 Dec 2008) | 5 lines
  
  Fix the final wrong-code test. The only remaining CompiledVsInterpreted relate to incorrect reference counts.
  
  This fixes a case where $x =& $arr[$in] incorrectly converted a $arr into an array.
  It also fix a memory leak involvinfg saved_refcount. saved_refcount shouldn't be saved in the return statement, and we do not know how many destructors will change its refcount. Instead, it should be saved after the destructors run.
........
  r2055 | paul.biggar | 2008-12-09 17:09:00 +0000 (Tue, 09 Dec 2008) | 2 lines
  
  Last chek over the manual, fixing some wording, and adding a section on compiling PHP for phc development. Though far from perfect, its probably good enough to release.
........
  r2056 | paul.biggar | 2008-12-09 17:09:24 +0000 (Tue, 09 Dec 2008) | 2 lines
  
  The README was out of date. Refer people to the manual instead.
........
  r2057 | paul.biggar | 2008-12-09 17:09:51 +0000 (Tue, 09 Dec 2008) | 2 lines
  
  Change the version number to 0.2.0.
........
  r2058 | paul.biggar | 2008-12-09 19:10:46 +0000 (Tue, 09 Dec 2008) | 2 lines
  
  Reindent the runtime files using GNU indent.
........
  r2059 | paul.biggar | 2008-12-09 20:21:50 +0000 (Tue, 09 Dec 2008) | 2 lines
  
  Move debug_zval_dump tests to unsupported.
........
  r2060 | paul.biggar | 2008-12-09 20:30:04 +0000 (Tue, 09 Dec 2008) | 2 lines
  
  Update the ChangeLog for 0.2.0.
........
  r2061 | paul.biggar | 2008-12-10 13:07:57 +0000 (Wed, 10 Dec 2008) | 2 lines
  
  Update changelog with entries from the old repository (after Sep 06, when we released 0.1.7).
........
  r2062 | paul.biggar | 2008-12-10 13:12:23 +0000 (Wed, 10 Dec 2008) | 4 lines
  
  Implement include_once and require_once. Unfortunately, the filenames, functions and line numbers reported in errors arent correct, but its good enough for now.
  
  Also add test for a register_shutdown_function when there is no call to die(). The registered function should still be called.
........
  r2063 | paul.biggar | 2008-12-10 13:36:27 +0000 (Wed, 10 Dec 2008) | 6 lines
  
  Another look over the changelog:
  
  Its now split into new features and bug fixes.
  Formatting is more attractive (in vim at least), though it breaks the formatting on old entries.
  More user-visible changes are moved to the top.
........
  r2064 | paul.biggar | 2008-12-10 15:04:16 +0000 (Wed, 10 Dec 2008) | 2 lines
  
  Include headers not mentioned in Makefile.am. Some important-ish headers weren't installed.
........
  r2068 | paul.biggar | 2008-12-11 18:42:09 +0000 (Thu, 11 Dec 2008) | 2 lines
  
  Remove unnecessary call.
........
  r2069 | paul.biggar | 2008-12-11 18:42:51 +0000 (Thu, 11 Dec 2008) | 2 lines
  
  I had assumed that there wouldnt be more than 2000 revisions. I'm now assuming there wont be 5000 revisions instead.
........